import org.springframework.jdbc.core.BeanPropertyRowMapper
import org.springframework.jdbc.core.JdbcTemplate

class FilmeRepository{
    lateinit var jdbcTemplate: JdbcTemplate

    fun iniciar(){
        jdbcTemplate = Conexao().conectar()
    }

    fun criarTabela(){
        jdbcTemplate.execute(
            """
                 create table filme(
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR (45),
                    diretor VARCHAR (45),
                    indicadoOscar BOOLEAN,
                    custoProducao DOUBLE
                 );
            """
        )
    }

    fun cadastrar(novoFilme: Filme){
        jdbcTemplate.update(
            """
                INSERT INTO filme (nome, diretor, indicadoOscar, custoProducao) values ('${novoFilme.nome}', '${novoFilme.diretor}', ${novoFilme.indicadoOscar}, ${novoFilme.custoProducao}) 
            """
        )
    }

    fun recuperar(codigo: Int): Filme?{
        return jdbcTemplate.queryForObject(
            """
               SELECT * FROM filme WHERE id = ${codigo}  
            """, BeanPropertyRowMapper(Filme::class.java)
        )
    }

    fun excluir(codigo: Int):Int{
        return jdbcTemplate.update(
            """
                DELETE FROM filme WHERE id = ${codigo} 
            """
        )
    }
}