import org.springframework.jdbc.core.BeanPropertyRowMapper
import org.springframework.jdbc.core.JdbcTemplate

class MusicaRepository {

    lateinit var jdbcTemplate: JdbcTemplate

    fun iniciar(){
        jdbcTemplate = Conexao.jdbcTemplate!!
    }

    fun criarTabela(){
        jdbcTemplate.execute(
                """
                 create table musica(
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    titulo VARCHAR (45),
                    artista VARCHAR (45),
                    dataCriacao DATE
                 );
            """
                )
    }

    fun cadastrar(novaMusica: Musica){
        jdbcTemplate.update(
            """
                INSERT INTO musica (titulo, artista, dataCriacao) values ('${novaMusica.titulo}', '${novaMusica.artista}', '${novaMusica.dataCriacao}') 
            """
        )
    }

    fun buscar(codigo: Int): Musica?{
        return jdbcTemplate.queryForObject(
            """
               SELECT * FROM musica WHERE id = $codigo  
            """, BeanPropertyRowMapper(Musica::class.java)
        )
    }

    fun excluir(codigo: Int):Int{
        return jdbcTemplate.update(
            """
                DELETE FROM musica WHERE id = $codigo 
            """
        )
    }

}

